
version: '3.8' 
 
services: 
  db: 
    image: postgres:latest 
    container_name: postgres_db 
    environment: 
      POSTGRES_DB: teledokdb      
      POSTGRES_USER: maxim          
      POSTGRES_PASSWORD: maxim    
    ports: 
      - "5432:5432"                         
    volumes: 
      - pg_data:/var/lib/postgresql/data    
 
volumes: 
  pg_data: